project:
  type: website
  output-dir: docs
  render:
    - OneSimplePlot.qmd
    - MultiplePlots.qmd
    - ThreeGroupsV1.qmd
    - ThreeGroupsV2.qmd
    - ggplot2.qmd
    - index.qmd

website:
  title: "Forest plots in R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
        contents: 
          - OneSimplePlot.qmd
          - MultiplePlots.qmd
          - ThreeGroupsV1.qmd
          - ThreeGroupsV2.qmd
          - ggplot2.qmd

format:
  html:
    theme:
      - united



